const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createDatabase } = require('./helpers/database.cjs');

test('Connection commerce enforces seller fees, chat access, inventory and delivery ownership', async () => {
 const db = await createDatabase();
 const [admin,buyer,a,b,outsider] = [601,602,603,604,605].map(n => '00000000-0000-4000-8000-000000000'+n);
 const q = async (sql,args=[]) => (await db.query(sql,args)).rows;
 const scalar = async (sql,args=[]) => Object.values((await q(sql,args))[0])[0];
 const as = async id => { await db.exec('reset role'); await q("select set_config('request.jwt.claim.sub',$1,false)",[id]); await db.exec('set role authenticated'); };
 const place = (key,items=[{product_id:960,quantity:1}],total=10000,recipient=['Buyer','0901234567','Cơ sở chính Nguyễn Văn Bảo']) => scalar("select public.request_connection_orders($1,$2,$3,'',$4::jsonb,$5,'{}',$6)",[...recipient,JSON.stringify(items),total,key]);
 try {
  for (const id of [admin,buyer,a,b,outsider]) await q('insert into auth.users(id,email) values($1,$2)',[id,id+'@test.invalid']);
  await q("update public.users set role='admin' where user_id=$1",[admin]);
  await q("update public.users set terms_accepted=true");
  await q("insert into public.products(id,seller_id,name,category,quantity,price) values(960,$1,'Book A','books',10,10000),(961,$1,'Book B','books',10,20000),(962,$2,'Book C','books',10,100000),(963,$1,'Last Book','books',1,5000)",[a,b]);
  // An existing chat must also become inaccessible until a fee is confirmed.
  const old = await scalar('insert into public.conversations default values returning id');
  await q('insert into public.conversation_members(conversation_id,user_id) values($1,$2),($1,$3)',[old,buyer,a]);
  await q("insert into public.messages(conversation_id,sender_id,content) values($1,$2,'Old private message')",[old,a]);
  await as(buyer);
  assert.equal(await scalar('select public.can_contact_seller($1)',[a]),false);
  assert.equal((await q('select * from public.messages where conversation_id=$1',[old])).length,0);
  await assert.rejects(q('select public.get_or_create_direct_conversation($1)',[a]));
  await assert.rejects(q("insert into public.messages(conversation_id,sender_id,content) values($1,$2,'Bypass')",[old,buyer]));
  assert.ok((await scalar('select public.get_or_create_direct_conversation($1)',[admin])).id,'Admin support remains open');
  await assert.rejects(place('wrong-price',undefined,1));
  const first = await place('minimum-fee');
  assert.equal(first.request_ids.length,1);
  assert.deepEqual(await place('minimum-fee'),first);
  assert.deepEqual(await scalar("select public.get_connection_receipt('minimum-fee')"),first);
  await assert.rejects(place('partial-fail',[{product_id:960,quantity:1},{product_id:962,quantity:99}],9910000));
  await assert.rejects(place('minimum-fee',[{product_id:960,quantity:2}],20000));
  const id = first.request_ids[0];
  let row = (await q('select * from public.connection_requests where id=$1',[id]))[0];
  assert.equal(Number(row.platform_fee),2000);
  assert.equal(new Date(row.expires_at)-new Date(row.created_at),86400000);
  assert.equal(Number(await scalar('select quantity from public.products where id=960')),9);
  await assert.rejects(q('select public.confirm_connection_fee($1)',[id]));
  await assert.rejects(q("update public.connection_requests set status='connected' where id=$1",[id]));
  await as(outsider);
  assert.equal(await scalar("select public.get_connection_receipt('minimum-fee')"),null);
  assert.equal((await q('select * from public.connection_requests')).length,0);
  assert.equal((await scalar('select public.get_connection_requests()')).requests.length,0);
  await assert.rejects(q('select public.confirm_connection_fee($1)',[id]));
  await assert.rejects(q('select public.cancel_connection_request($1)',[id]));
  await as(a);
  assert.equal((await q("select * from public.connection_notifications where event='seller_fee_due'")).length,1);
  const connected = await scalar('select public.confirm_connection_fee($1)',[id]);
  assert.equal(connected.conversation_id,old);
  assert.equal((await scalar('select public.confirm_connection_fee($1)',[id])).conversation_id,old);
  assert.equal((await q("select * from public.connection_fee_entries where kind='platform'")).length,1);
  await as(buyer);
  assert.equal(await scalar('select public.can_contact_seller($1)',[a]),true);
  assert.equal((await q('select * from public.messages where conversation_id=$1',[old])).length,1);
  await q("insert into public.messages(conversation_id,sender_id,content) values($1,$2,'Unlocked')",[old,buyer]);
  await assert.rejects(q("select public.choose_connection_delivery($1,'passit','')",[id]));
  await as(a);
  await q("select public.choose_connection_delivery($1,'passit','15:00 tại cổng trường')",[id]);
  await q("select public.choose_connection_delivery($1,'passit','')",[id]);
  assert.equal(Number(await scalar("select amount from public.connection_fee_entries where request_id=$1 and kind='delivery'",[id])),5000);
  await assert.rejects(q("select public.choose_connection_delivery($1,'direct','')",[id]));
  await assert.rejects(q("select public.admin_update_connection_delivery($1,'arranging')",[id]));
  await as(admin);
  assert.equal((await q("select * from public.connection_notifications where event='delivery_requested'")).length,1);
  assert.match((await q("select message from public.connection_notifications where event='delivery_requested'"))[0].message,/chưa thu tiền thật.*Admin sẽ liên hệ/s);
  const adminRequests=(await scalar('select public.get_connection_requests()')).requests;
  assert.ok(adminRequests.some(request=>request.id===id));
  assert.ok(adminRequests.find(request=>request.id===id).buyer_contact);
  assert.ok(adminRequests.find(request=>request.id===id).seller_contact);
  await assert.rejects(q("select public.admin_update_connection_delivery($1,'delivered')",[id]));
  await as(buyer);
  await assert.rejects(q('select public.buyer_confirm_connection_received($1)',[id]));
  await as(admin);
  await q("select public.admin_update_connection_delivery($1,'arranging')",[id]);
  await q("select public.admin_update_connection_delivery($1,'delivered')",[id]);
  await as(buyer);
  assert.equal(await scalar("select delivery_status from public.connection_requests where id=$1",[id]),'delivered');
  await q('select public.buyer_confirm_connection_received($1)',[id]);
  assert.equal(await scalar("select delivery_status from public.connection_requests where id=$1",[id]),'completed');
  const split=await place('multi',[{product_id:960,quantity:2},{product_id:961,quantity:2},{product_id:962,quantity:1}],160000);
  assert.equal(split.request_ids.length,2);
  const splitRows = await q('select * from public.connection_requests where id=any($1::bigint[]) order by subtotal',[split.request_ids]);
  assert.deepEqual(splitRows.map(r=>Number(r.platform_fee)),[3000,5000]);
  const cancel=splitRows[0].id;
  await q('select public.cancel_connection_request($1)',[cancel]);
  await q('select public.cancel_connection_request($1)',[cancel]);
  assert.equal(Number(await scalar('select quantity from public.products where id=960')),9);
  const exp=splitRows[1].id;
  await db.exec('reset role');
  await q("update public.connection_requests set expires_at=now()-interval '1 second' where id=$1",[exp]);
  await q("update public.products set status='deleted' where id=962");
  await as(b);
  assert.equal((await scalar('select public.confirm_connection_fee($1)',[exp])).success,false);
  await q('select public.expire_connection_requests()');
  assert.equal(Number(await scalar('select quantity from public.products where id=962')),10);
  assert.equal(await scalar('select status from public.products where id=962'),'deleted');
  assert.equal(await scalar('select public.can_contact_seller($1)',[buyer]),false);
  await as(buyer); const direct=(await place('direct')).request_ids[0];
  await db.exec('reset role');await q('update private.connection_settings set auto_confirm=false');
  await as(a);await assert.rejects(q('select public.confirm_connection_fee($1)',[direct]));
  await db.exec('reset role');await q('update private.connection_settings set auto_confirm=true');
  await as(a);await q('select public.confirm_connection_fee($1)',[direct]);
  await q("select public.choose_connection_delivery($1,'direct','')",[direct]);
  assert.equal((await q("select * from public.connection_fee_entries where request_id=$1 and kind='delivery'",[direct])).length,0);
  await q('select public.seller_mark_connection_delivered($1)',[direct]);
  assert.equal(await scalar("select delivery_status from public.connection_requests where id=$1",[direct]),'seller_delivered');
  await as(buyer);
  await assert.rejects(q('select public.seller_mark_connection_delivered($1)',[direct]));
  await q('select public.buyer_confirm_connection_received($1)',[direct]);
  assert.equal(await scalar("select delivery_status from public.connection_requests where id=$1",[direct]),'completed');
  await as(a);
  const image=JSON.stringify(['https://xecxofmogvqysejjpxvl.supabase.co/storage/v1/object/public/products/'+a+'/book.jpg']);
  const free=await scalar("select public.create_free_product('Free Book','books',1,10000,'Complete book description',$1::jsonb,'Mới','Cơ sở chính Nguyễn Văn Bảo','free-1')",[image]);
  assert.equal(free.listing_fee,0);assert.equal(free.boost_fee,0);
  assert.equal(await scalar('select item_condition from public.products where id=$1',[free.id]),'Mới');
  await assert.rejects(q("select public.create_free_product('Bad','books',1,10000,'short',$1::jsonb,'Mới','Cơ sở chính Nguyễn Văn Bảo','bad')",[image]));
  await as(buyer);
  const noDetails=await place('no-recipient-details',undefined,10000,['','','']);
  const noDetailsRow=(await q('select recipient_name,recipient_phone,recipient_address from public.connection_requests where id=$1',[noDetails.request_ids[0]]))[0];
  assert.deepEqual(Object.values(noDetailsRow),['','','']);
  await assert.rejects(place('invalid-optional-phone',undefined,10000,['','1','']));
  const stockout=await place('sold-out',[{product_id:963,quantity:1}],5000);
  await db.exec('reset role');
  assert.equal(await scalar('select quantity from public.products where id=963'),0);
  assert.equal(await scalar('select status from public.products where id=963'),'deleted');
  await as(buyer);
  await q('select public.cancel_connection_request($1)',[stockout.request_ids[0]]);
  await db.exec('reset role');
  assert.equal(await scalar('select quantity from public.products where id=963'),1);
  assert.equal(await scalar('select status from public.products where id=963'),'active');
  await db.exec('reset role');
  assert.equal(Number(await scalar('select count(*) from public.orders')),0);
  assert.equal(Number(await scalar('select count(*) from public.wallet_transactions')),0);
  await as(admin);await q('select public.set_iuh_trial_mode(false)');await db.exec('reset role');
  const legacy=await scalar("insert into public.orders(order_code,buyer_id,recipient_name,recipient_phone,recipient_address,shipping_method,payment_method,subtotal,total_amount,status,payment_status) values('OLD-PAID',$1,'Buyer','0901234567','Campus','meet','cash',100000,105000,'completed','paid') returning id",[buyer]);
  await q("insert into public.order_items(order_id,product_id,seller_id,product_name,price,quantity,subtotal) values($1,962,$2,'Book C',100000,1,100000)",[legacy,b]);
  await as(buyer);assert.equal(await scalar('select public.can_contact_seller($1)',[b]),false,'Old COD payment alone is not a paid platform fee');
  await db.exec('reset role');await q('update public.orders set platform_fee_paid_at=now() where id=$1',[legacy]);
  await as(buyer);assert.equal(await scalar('select public.can_contact_seller($1)',[b]),true,'Previously paid platform fee keeps historical chat available');
  await db.exec('reset role');
  assert.equal(await scalar("select has_function_privilege('authenticated','public.create_order(text,text,text,text,text,numeric,text,numeric,numeric,jsonb,bigint[],text)','execute')"),false);
  assert.equal(await scalar("select has_function_privilege('authenticated','public.create_product_with_boost(text,text,integer,numeric,text,jsonb,boolean,text)','execute')"),false);
 } finally { await db.close(); }
});
