const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createDatabase } = require('./helpers/database.cjs');

test('Trial orders follow admin payment → seller acceptance/delivery → admin completion → buyer acknowledgement', async () => {
    const db = await createDatabase({ legacyCommerce: true });
    const ids = ['101', '102', '103', '104'].map(n => '00000000-0000-4000-8000-000000000' + n);
    const [admin, buyer, seller, outsider] = ids;
    const q = async (sql, args = []) => (await db.query(sql, args)).rows;
    const scalar = async (sql, args = []) => Object.values((await q(sql, args))[0])[0];
    const as = async id => { await db.exec('reset role'); await q("select set_config('request.jwt.claim.sub',$1,false)", [id]); await db.exec('set role authenticated'); };
    try {
        for (const id of ids) await q('insert into auth.users(id,email) values($1,$2)', [id, id + '@test.invalid']);
        await q("update public.users set role='admin' where user_id=$1", [admin]);
        await q("insert into public.products(id,seller_id,name,category,quantity,price) values(900,$1,'Book','books',10,100000)", [seller]);
        await as(buyer);
        const order = await scalar("select public.create_order('Buyer','0901234567','Cơ sở chính Nguyễn Văn Bảo','','mid',5000,'trial',105000,110000,'[{\"product_id\":900,\"quantity\":1}]','{}','handoff-order-0001')");
        const id = order.order_id;
        assert.equal(order.payment_status, 'unpaid');
        // Migrate with an existing unpaid order and verify that its lifecycle still works.
        await db.exec('reset role');
        await db.exec(require('node:fs').readFileSync('IUH shop/supabase/migrations/20261008105343_seller_connection_workflow.sql','utf8'));
        await as(seller);
        assert.equal((await scalar('select public.get_my_orders()')).length, 0);
        assert.equal((await q('select id from public.orders where id=$1', [id])).length, 0);
        await assert.rejects(q("select public.update_order_status($1,'shipping')", [id]));
        await assert.rejects(q('select public.admin_confirm_order_payment($1,null)', [id]));
        await as(admin);
        await assert.rejects(q("select public.update_order_status($1,'completed')", [id]));
        await q('select public.admin_confirm_order_payment($1,null)', [id]);
        await q('select public.admin_confirm_order_payment($1,null)', [id]);
        assert.equal(await scalar('select status from public.orders where id=$1', [id]), 'confirmed');
        assert.equal(Number(await scalar('select captured_amount from public.orders where id=$1', [id])), 110000);
        assert.equal(Number(await scalar('select count(*) from public.trial_financial_entries')), 0);
        await assert.rejects(q("select public.update_order_status($1,'shipping')", [id]));
        await assert.rejects(q("select public.update_order_status($1,'completed')", [id]));
        await as(outsider);
        assert.equal((await scalar('select public.get_my_orders()')).length, 0);
        await assert.rejects(q("select public.update_order_status($1,'shipping')", [id]));
        await as(seller);
        assert.equal((await scalar('select public.get_my_orders()'))[0].id, id);
        assert.equal(Number(await scalar('select count(*) from public.order_notifications')), 1);
        await assert.rejects(q("select public.update_order_status($1,'delivered')", [id]));
        await q("select public.update_order_status($1,'shipping')", [id]);
        await q("select public.update_order_status($1,'shipping')", [id]);
        await q("select public.update_order_status($1,'delivered')", [id]);
        await assert.rejects(q("select public.update_order_status($1,'completed')", [id]));
        await as(buyer);
        await assert.rejects(q('select public.confirm_order_received($1)', [id]));
        await assert.rejects(q("select public.update_order_status($1,'completed')", [id]));
        await as(admin);
        assert.equal(Number(await scalar("select count(*) from public.order_notifications where event='delivered'")), 1);
        await q("select public.update_order_status($1,'completed')", [id]);
        await q("select public.update_order_status($1,'completed')", [id]);
        await q('select public.settle_online_order($1)', [id]);
        const entries = await q('select kind,amount from public.trial_financial_entries order by kind');
        assert.deepEqual(entries.map(r => [r.kind, Number(r.amount)]), [['platform', 5000], ['seller', 100000], ['shipping', 5000]]);
        assert.equal(Number(await scalar('select coalesce(sum(balance+pending),0) from public.iuh_wallets')), 0);
        const detail = await scalar("select public.admin_operation_detail('orders',$1)", [String(id)]);
        assert.equal(detail.record.status, 'completed');
        assert.equal(detail.finance.payout_status, 'trial_recorded');
        await as(seller);
        assert.equal((await q('select * from public.trial_financial_entries')).length, 1);
        assert.equal(await scalar('select public.can_contact_seller($1)',[buyer]),true);
        await assert.rejects(q("update public.trial_financial_entries set amount=1"));
        await assert.rejects(q('select public.confirm_order_received($1)', [id]));
        await as(buyer);
        assert.equal((await q('select * from public.trial_financial_entries')).length, 0);
        assert.equal(Number(await scalar("select count(*) from public.order_notifications where event='completed' and not is_read")), 1);
        await q('select public.confirm_order_received($1)', [id]);
        await q('select public.confirm_order_received($1)', [id]);
        assert.ok((await scalar('select public.get_my_orders()'))[0].buyer_confirmed_at);
        assert.equal(Number(await scalar('select count(*) from public.order_notifications where not is_read')), 0);
        const pack = await scalar("select public.purchase_service_package('personal','trial','handoff-package-0001','{}')");
        assert.equal(pack.status, 'pending');
        await as(admin);
        await q("select public.approve_service_package_payment('handoff-package-0001',null)");
        await q("select public.approve_service_package_payment('handoff-package-0001',null)");
        assert.equal(Number(await scalar("select sum(amount) from public.trial_financial_entries where kind='package'")), 19000);
        assert.equal(Number(await scalar("select count(*) from public.trial_financial_entries where kind='package'")), 1);
    } finally { await db.close(); }
});
