const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('IUH shop/JS/password-recovery.js', 'utf8');
function fixture(options = {}) {
 const elements = new Map();
 function element(id) { if (!elements.has(id)) elements.set(id, { hidden: id === 'resetPasswordForm', value:'', disabled:false, textContent:'', classList:{toggle(){}}, setAttribute(){}, focus(){}, reportValidity:()=>true, reset(){}, addEventListener(type,fn){this[type]=fn;}, querySelector(){return element(id+'Button');} }); return elements.get(id); }
 const calls={send:0,update:0,set:0,signout:0}; let config;
 const auth={resetPasswordForEmail:async(email,args)=>{calls.send++;calls.email=email;calls.redirect=args.redirectTo;if(options.sendThrow)throw Error('offline');return {error:options.sendError};},setSession:async()=>{calls.set++;return {error:options.invalid?{status:401}:null};},getUser:async()=>({data:{user:options.invalid?null:{id:'user'}},error:null}),updateUser:async args=>{calls.update++;if(options.updateThrow)throw Error('offline');return {error:options.updateError};},signOut:async()=>{calls.signout++;if(options.logoutThrow)throw Error('offline');return {error:null};}};
 const location={hash:options.hash||'',search:'',pathname:'/IUH%20shop/HTML/quenmatkhau.html',href:'https://passit.example/IUH%20shop/HTML/quenmatkhau.html',protocol:options.protocol||'https:'};
 const ctx={URL,URLSearchParams,Date,document:{getElementById:element},location,history:{replaceState(a,b,url){calls.clean=url;}},setInterval:()=>1,clearInterval(){},window:{IUHCaptcha:{takeToken:()=> 'test-token',reset(){}},addEventListener(){},supabase:{createClient(u,k,c){config=c;return {auth};}}}};
 vm.createContext(ctx);vm.runInContext(source,ctx);
 return {elements,element,calls,auth,options,config,flush:()=>new Promise(resolve=>setImmediate(resolve)),submit:async id=>element(id).submit({preventDefault(){}})};
}
const link='#type=recovery&access_token=test-access&refresh_token=test-refresh';
test('request uses the same origin callback and neutral confirmation, deduplicates repeated clicks',async()=>{let f=fixture();f.element('recoveryEmail').value=' user@example.com ';await Promise.all([f.submit('requestResetForm'),f.submit('requestResetForm')]);assert.equal(f.calls.send,1);assert.equal(f.calls.email,'user@example.com');assert.equal(f.calls.redirect,'https://passit.example/IUH%20shop/HTML/quenmatkhau.html');assert.match(f.element('recoveryMessage').textContent,/Nếu email/);await f.submit('requestResetForm');assert.equal(f.calls.send,1)});
test('network error unlocks request for retry',async()=>{let f=fixture({sendThrow:true});await f.submit('requestResetForm');assert.equal(f.element('requestResetFormButton').disabled,false);f.options.sendThrow=false;await f.submit('requestResetForm');assert.equal(f.calls.send,2)});
test('rate limit applies cooldown',async()=>{let f=fixture({sendError:{status:429}});await f.submit('requestResetForm');assert.equal(f.element('requestResetFormButton').disabled,true)});
test('file URLs cannot generate unusable recovery links',async()=>{let f=fixture({protocol:'file:'});await f.submit('requestResetForm');assert.equal(f.calls.send,0)});
test('ordinary page visit cannot change password using an existing login',async()=>{let f=fixture();await f.submit('resetPasswordForm');assert.equal(f.calls.update,0);assert.equal(f.config.auth.persistSession,false);assert.equal(f.config.auth.detectSessionInUrl,false)});
test('invalid or expired link does not expose reset form',async()=>{let f=fixture({hash:link,invalid:true});await f.flush();assert.equal(f.element('resetPasswordForm').hidden,true);assert.match(f.element('recoveryMessage').textContent,/hết hạn/);assert.equal(f.calls.clean,'/IUH%20shop/HTML/quenmatkhau.html')});
test('non-recovery callback is rejected before using credentials',async()=>{let f=fixture({hash:link.replace('recovery','signup')});await f.flush();assert.equal(f.calls.set,0)});
test('valid callback checks server identity, removes URL tokens and enables form',async()=>{let f=fixture({hash:link});await f.flush();assert.equal(f.calls.set,1);assert.equal(f.element('resetPasswordForm').hidden,false);assert.equal(f.element('resetPasswordFormButton').disabled,false);assert.ok(f.calls.clean)});
test('password length and confirmation block writes',async()=>{let f=fixture({hash:link});await f.flush();f.element('newPassword').value='short';await f.submit('resetPasswordForm');f.element('newPassword').value='long-password';f.element('confirmNewPassword').value='different';await f.submit('resetPasswordForm');assert.equal(f.calls.update,0)});
test('successful reset is single-submit and remains successful if logout fails',async()=>{let f=fixture({hash:link,logoutThrow:true});await f.flush();f.element('newPassword').value=f.element('confirmNewPassword').value='new-password';await Promise.all([f.submit('resetPasswordForm'),f.submit('resetPasswordForm')]);assert.equal(f.calls.update,1);assert.equal(f.calls.signout,1);assert.equal(f.element('resetPasswordForm').hidden,true);assert.match(f.element('recoveryMessage').textContent,/thành công/);await f.submit('resetPasswordForm');assert.equal(f.calls.update,1)});
test('failed password write keeps form available for retry',async()=>{let f=fixture({hash:link,updateThrow:true});await f.flush();f.element('newPassword').value=f.element('confirmNewPassword').value='new-password';await f.submit('resetPasswordForm');assert.equal(f.element('resetPasswordFormButton').disabled,false);f.options.updateThrow=false;await f.submit('resetPasswordForm');assert.equal(f.calls.update,2)});
