const fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const base=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(base,p),'utf8');
const ident=s=>'"'+s.replaceAll('"','""')+'"';
async function createDatabase(){
 const db=await PGlite.create();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create role supabase_admin;
 create schema auth;create schema storage;create schema private;
 create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.role() returns text language sql stable as $$select current_user::text$$;
 create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,owner_id text,owner uuid,metadata jsonb);
 alter table storage.objects enable row level security;
 create function storage.foldername(text) returns text[] language sql immutable as $$select (string_to_array($1,'/'))[1:array_length(string_to_array($1,'/'),1)-1]$$;
 grant usage on schema public,private,auth,storage to anon,authenticated;
 grant execute on all functions in schema auth,storage to anon,authenticated;`);
 const schema=JSON.parse(read('audit/pre-fix-tables.json'));
 const tables=[...new Set(schema.columns.map(c=>c.relname))];
 for(const table of tables){const columns=schema.columns.filter(c=>c.relname===table).map(c=>{
  const serial=c.attname==='id'&&['bigint','integer'].includes(c.data_type)&&!c.default_value;
  return `${ident(c.attname)} ${c.data_type}${serial?' generated by default as identity':c.default_value?' default '+c.default_value:''}${c.attnotnull?' not null':''}`;
 });await db.exec(`create table public.${ident(table)}(${columns.join(',')});alter table public.${ident(table)} enable row level security;`);}
 for(const c of schema.constraints.filter(c=>!c.definition.startsWith('FOREIGN KEY'))){await db.exec(`alter table public.${ident(c.relname)} add constraint ${ident(c.conname)} ${c.definition}`);}
 const meta=JSON.parse(read('audit/db-2.json'))[0].json_build_object;
 for(const i of JSON.parse(read('audit/pre-fix-indexes.json'))){if(!(await db.query('select 1 from pg_class where relname=$1',[i.indexname])).rows.length)await db.exec(i.indexdef);}
 for(const c of schema.constraints.filter(c=>c.definition.startsWith('FOREIGN KEY'))){await db.exec(`alter table public.${ident(c.relname)} add constraint ${ident(c.conname)} ${c.definition}`);}
 for(const f of meta.private_functions)await db.exec(f.definition);
 const functions=JSON.parse(read('audit/db-0.json'));
 for(const f of functions)await db.exec(f.definition);
 for(const i of JSON.parse(read('audit/pre-fix-indexes.json'))){if(!(await db.query('select 1 from pg_class where relname=$1',[i.indexname])).rows.length)await db.exec(i.indexdef);}
 for(const p of JSON.parse(read('audit/db-1.json'))){const roles=p.roles.replace(/[{}]/g,'');await db.exec(`create policy ${ident(p.policyname)} on ${ident(p.schemaname)}.${ident(p.tablename)} for ${p.cmd} to ${roles}${p.qual?' using ('+p.qual+')':''}${p.with_check?' with check ('+p.with_check+')':''}`);}
 for(const t of JSON.parse(read('audit/db-4.json'))[0].json_build_object.triggers)await db.exec(t.definition);
 await db.exec('grant all on all tables in schema public,storage to authenticated;grant select on all tables in schema public to anon;grant usage,select on all sequences in schema public to authenticated;');
 try {for(const file of fs.readdirSync(path.join(base,'IUH shop/supabase/migrations')).filter(n=>n.endsWith('.sql')).sort())await db.exec(read('IUH shop/supabase/migrations/'+file));}
 catch(err){await db.close();throw new Error('Migration: '+err.message+' '+(err.detail||'')+' at '+(err.position||''));}
 return db;
}
module.exports={createDatabase};

